server:
  port: 5001

spring:
  application:
    name: c-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: c-user-center                       # 路由ID，没有固定规则但要求唯一，建议配置服务名称
          uri: http://127.0.0.1:1001              # 匹配提供服务的路由地址
          predicates:
            - Path=/api-user/**                   # 断言，路径匹配进行路由
