server:
  port: 1001
spring:
  application:
    name: c-user-center


logging:
  config: classpath:logback-spring.xml

##自定义curator分布式锁配置
curator:
  zk:
    # 初始休眠时间
    base-sleep-time: 1000
    # 重试次数
    max-retries: 5
    # session超时时间
    session-time-out: 60000
    # zookeeper 地址
    zookeeper-uri: '192.168.1.0:2181,192.168.1.1:2181,192.168.1.2:2181'
    # 命名空间
    namespace: 'zk-lock'
    # 子节点路径
    lock-path: 'product_stock_lock'
    # 连接超时时间
    connection-time-out: 5000
    product-lock-path: '/lock-path'
