server:
  port: 1001
spring:
  application:
    name: c-user-center

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    druid:
      filters: stat,wall,slf4j
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 'x' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  rabbitmq:
    addresses: 10.2.9.150:5672
    username: root
    password: 123456
    connection-timeout: 15000
    virtual-host: /t
      # 确认消息已经发送到队列中
    publisher-returns: true
      # 确认消息已经发送到交换机中
    template:
        # 保证监听有效
      mandatory: true
    listener:
      simple:
          # 手动确认
        acknowledge-mode: manual
        # 同一个队列启动几个消费者
        concurrency: 5
        # 启动消费者最大数量
        max-concurrency: 10
      # 消息确认ACK机制
    publisher-confirms: true

  jackson:
    default-property-inclusion: non_null

# rocketMq
rocketmq:
  name-server: 192.168.19.130:9876
  producer:
    # 自定义组名
    group: 'demo_topic'
    # 消息发送超时时间
    send-message-timeout: 5000

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      alibaba:
        nacos: ERROR


##自定义curator分布式锁配置

curator:
  zk:
    # 初始休眠时间
    base-sleep-time: 1000
    # 重试次数
    max-retries: 5
    # session超时时间
    session-time-out: 60000
    # zookeeper 地址
    zookeeper-uri: '10.2.9.150:2181,10.2.9.151:2181,10.2.9.152:2181'
    # 命名空间
    namespace: 'zk-lock'
    # 子节点路径
    lock-path: 'product_stock_lock'
    # 连接超时时间
    connection-time-out: 5000
    product-lock-path: '/lock-path'


