server:
  port: 1314

spring:
  elasticsearch:
      rest:
        uris: ["http://10.2.9.150:9200","http://10.2.9.151:9200","http://10.2.9.152:9200"]

  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 10.2.9.150:9300,10.2.9.151:9300,10.2.9.152:9300
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: m,[<}L;p1mysqlcy
    url: jdbc:mysql://10.2.9.151:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true
    username: bjparkcy
    druid:
      filters: stat,wall,slf4j
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 'x' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.smart.search.bean

